1_LayoutPage/Models/ConcatModel.cs
using System.ComponentModel.DataAnnotations;

namespace _1_LayoutPage.Models
{
	public class ContactModel
	{

		[Required(ErrorMessage ="Bu alan zorunludur")]
		public string Email { get; set; }


		[Required(ErrorMessage ="Mesaj alanı zorunludur")]
		public string Message { get; set; }
	}
}

1_LayoutPage/Models/ErrorViewModel.cs
namespace _1_LayoutPage.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

1_LayoutPage/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace _1_LayoutPage.Controllers
{
	public class AboutController : Controller
	{
		public IActionResult Index()
		{
			return View();

		}


	}
}

1_LayoutPage/Controllers/ContactController.cs
using _1_LayoutPage.Models;
using Microsoft.AspNetCore.Mvc;

namespace _1_LayoutPage.Controllers
{
	public class ContactController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}


		[HttpPost]
		public IActionResult Index(ContactModel model)
		{
			return View();
		}

	}
}

1_LayoutPage/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;

namespace _1_LayoutPage.Controllers
{
	public class DemoController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

1_LayoutPage/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace _1_LayoutPage.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

1_LayoutPage/Views/About/Index.cshtml
@{
	//Layout = "~/Views/Shared/_Sablon.cshtml"; // layout ayarlaması view start dosyasından yapıldı....
}

<h1>ben about sayfası...</h1>




<!--
	section => Layout pagelerde render edilmesi için oluşturulan alanladır...
-->

@section MySection{

	<div id="sol">
		ben about indexinin özelliştirilmiş bölgesiyim...
	</div>


}

1_LayoutPage/Views/Contact/Index.cshtml
@*@model _1_LayoutPage.Models.ContactModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers*@
@model ContactModel

@{
	ViewData["Title"] = "Index";
	//Layout = "~/Views/Shared/_Sablon.cshtml";
}

<h1>Index</h1>

<form asp-action="Index">
	<input asp-for="Email" placeholder="EMail Adresiniz" />
	<span asp-validation-for="Email"></span>
	<br />
	<textarea asp-for="Message" placeholder="Mesajınızı bu bölüme yazınız"></textarea>
	<span asp-validation-for="Message"></span>
	<br />
	<input type="submit" value="Gönder" />
</form>




<!--
	ValidationScript => renderbody'de depil layut'ın istenilen bölgesinde render edilir...
-->
@section ValidationScript{
	<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
	}

1_LayoutPage/Views/Demo/Index.cshtml
@{
	Layout = null; // View startta belirtilen Layout'u kullanma...
}

1_LayoutPage/Views/Home/Index.cshtml
@{
//	Layout = "~/Views/Shared/_Sablon.cshtml"; // Bu view'ın layoutu belirtilen pathdeki view'dır..
}


ben bir view'ım.....

1_LayoutPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

1_LayoutPage/Views/Shared/_Sablon.cshtml
<html>
<head>

	<style>
		header{
			height:70px;
			background-color:black;
		}
		.container{
			width:900px;
			margin:0 auto;
		}
		input{
			border:none;
			background-color:white;
			border-radius:10px;
			margin:20px auto;
		}

		#sol{
			width:200px;
			background-color:red;
		}
	</style>
</head>
<body>
	<header>
		<div class="container">
			<input type="text" placeholder="arama yapın" />
		</div>
	</header>
	<a asp-action="Index" asp-controller="Home">Anasayfa</a>
	<a asp-action="Index" asp-controller="About">Hakkımızda</a>
	<a asp-action="Index" asp-controller="Contact">Iletişim</a>

	@*@RenderBody() => bu view'I layout olark kullanan viewları bu bölümde render et...*@




	@RenderBody()


	<!--eğer section tanımlıysa sectionı render et...-->
	@if (IsSectionDefined("MySection"))
	{
		@RenderSection("MySection")
	}



	<script src="~/lib/jquery/dist/jquery.js"></script>

	@if (IsSectionDefined("ValidationScript"))
	{
		@RenderSection("ValidationScript")
	}


	@*
		BU scriptler sadece Contact sayfasında olması gerekir. çünkü validasyon sadece o sayfada yapılacaktır...	
	<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
	
	*@
		




</body>
</html>