3_ViewComponent/Components/BoxViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace _3_ViewComponent.Components
{

	// BoxViewComponent sınıfınımız view component gibi davranabilmesi için ViewComponent interfacesinden türemesi gerekir.


	// Kural;
	// 1) ViewComponent sınıf içerisinde Invoke isminde bir metot tanımlanmalıdır...

	public class BoxViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			List<string> ogrenciler = new List<string>();

			ogrenciler.Add("İsmail");
			ogrenciler.Add("Büşra");
			ogrenciler.Add("Onur");
			ogrenciler.Add("Ziya");

			return View(ogrenciler); // Views>Shared>Compoents>Box klasörü içerisinde ki default.cshtml isimli dosyayı döner.. yani her bir component için bu dosyası bu pathde oluşturmak gerekir...
		}
	}
}

3_ViewComponent/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace _3_ViewComponent.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

3_ViewComponent/Controllers/SayacController.cs
using Microsoft.AspNetCore.Mvc;

namespace _3_ViewComponent.Controllers
{
	public class SayacController : Controller
	{
		int i = 0;
		string str;
		public IActionResult Index()
		{
			str = "Bt Akademi";
			return View(i);
		}

		[HttpPost]
		// parametreiyi overload edebilmek için tanımladık..
		public IActionResult Index(string str)
		{
			i++;
			return View(i);
		}
	}
}

3_ViewComponent/Views/Home/Index.cshtml
<html>
<head>
</head>
<body>

	<!--View componeti bura çağırıyoruz...-->
	@await Component.InvokeAsync("Box")

	<a href="@Url.Action("Index","Sayac")"> sayac'a git</a>


</body>
</html>

3_ViewComponent/Views/Sayac/Index.cshtml
@model int

<h1>@Model</h1>

<form action="@Url.Action("Index","Sayac")" method="post">
	<input type="submit" value="Arttır" />
</form>

3_ViewComponent/Views/Shared/Components/Box/Default.cshtml
@model List<string>
<ul>
	@foreach (var item in Model)
	{
		<li>@item</li>
	}
</ul>